export const tagTypes = {
  auth: "Auth",
  users: "Users",
  earning: "Earning",
  deliveryManagement: "DeliveryManagement",
  orderManagement: "OrderManagement",
  gear: "Gear",
  package: "Package",
  category: "Category",
  workshop: "Workshop",
  report: "Report",
  commissionSetup: "CommissionSetup",
  feedback: "Feedback",
  profile: "Profile",
  setting: "Setting",
  conversation: "Conversation",
  interactionManagement: "InteractionManagement",
  coupon: "Coupon",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.users,
  tagTypes.orderManagement,
  tagTypes.gear,
  tagTypes.package,
  tagTypes.category,
  tagTypes.workshop,
  tagTypes.commissionSetup,
  tagTypes.feedback,
  tagTypes.profile,
  tagTypes.setting,
  tagTypes.conversation,
  tagTypes.deliveryManagement,
  tagTypes.earning,
  tagTypes.interactionManagement,
  tagTypes.report,
  tagTypes.coupon,
];
